CREATE DATABASE IF NOT EXISTS $DB_NAME;

CREATE USER IF NOT EXISTS '$USER_DBA'@'$HOST' IDENTIFIED BY '$PASSOWRD';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$USER_DBA'@'$HOST';

CREATE USER IF NOT EXISTS '$USERNAME'@'$HOST' IDENTIFIED BY '$PASSOWRD' PASSWORD EXPIRE INTERVAL 365 DAY;
GRANT
    DELETE,
    EXECUTE,
    INSERT,
    SELECT,
    UPDATE
ON $DB_NAME.* TO '$USERNAME'@'$HOST';
